---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-jboss
    description: Application template for SpringBoot REST + Red Hat SSO demo application.
    tags: javaee,java,jboss,xpaas,sso
    version: 1.3.2
  name: secured-springboot-rest
labels:
  template: secured-springboot-rest
  xpaas: 1.3.2
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: secured-springboot-rest
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
  value: ''
  required: false
- description: The URL for the SSO server (e.g. https://secure-sso-myproject.example.com/auth).  This
    is the URL through which the user will be redirected when a login or token is
    required by the application.
  name: SSO_URL
  value: https://secure-sso-sbr.e8ca.engint.openshiftapps.com
  required: true
- description: The RH-SSO realm to be used.
  name: REALM
  value: master
  required: true
- description: Realm's public key.
  name: REALM_PUBLIC_KEY
  value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjoVg6150oqh7csrGMsttu7r+s4YBkYDkKrg2v6Gd5NhJw9NKnFlojPnLPoDSlxpNpN2sWegexcsFdDdmtuMzTxQ3hnkFWHDDXsyfj2fKQwDjgcxg95nRaaI+/OGhWbEsGdt/A5jxg2f4Vp4VLTwCj7Ujq4hVx67vO/zbJ2k0cD2uz5T731tvqweC7H/Os+G8B1+PpH5e1jGkDPZohe4ERCEdwNcC9IAt1tPr/LKfh+84hOkE3i9mGG/LGUiJShtw7ia2jXTMb1JErlJsLJOjh+guz6OztQOICN//+rRA4AACB//+IeJ8mr/jN/dww+RfYyeAd/SId56ae8H4SE4HQQIDAQAB
  required: true
- description: RH-SSO client id.
  name: CLIENT_ID
  value: demoapp
  required: true
- description: RH-SSO secret.
  name: SECRET
  value: cb7a8528-ad53-4b2e-afb8-72e9795c27c8
  required: true
