apiVersion: v1
kind: Template
metadata:
  name: rest-secured
  labels:
    app.kubernetes.io/part-of: secured-api-example
    app.openshift.io/runtime-version: "2.5.10"
    app.openshift.io/runtime: rh-spring-boot
    app.kubernetes.io/name: secured-api
    app.kubernetes.io/component: frontend
  annotations:
    iconClass: icon-spring
    tags: spring-boot, rest, java, microservice
    openshift.io/display-name: Spring Boot - REST Http Endpoint
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://appdev.openshift.io/docs/spring-boot-runtime.html#mission-secured-spring-boot"
    app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
    description: >-
      The REST API Level 0 Mission provides a basic example of mapping business operations to a remote procedure call endpoint over HTTP using a REST framework.
parameters:
- name: RUNTIME_VERSION
  displayName: OpenJDK 8 image version to use
  description: Specifies which version of the OpenShift OpenJDK 8 image to use
  value: "1.3"
  required: true
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: ARTIFACT_COPY_ARGS
  description: Syntax to be used to copy uberjar files to the target directory
  displayName: Copy Args
  value: '*.jar'
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: Maven Nexus Repository to be used during build phase
  displayName:
  required: false
- name: SSO_AUTH_SERVER_URL
  description: The SSO Server URL
  displayName:
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rest-secured
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime
  spec:
    tags:
    - name: "${RUNTIME_VERSION}"
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/openjdk-8:${RUNTIME_VERSION}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: rest-secured
    labels:
      app.kubernetes.io/part-of: secured-api-example
      app.openshift.io/runtime-version: "2.5.10"
      app.openshift.io/runtime: rh-spring-boot
      app.kubernetes.io/name: secured-api
      app.kubernetes.io/component: frontend
    annotations:
      app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rest-secured:2.5.10-4
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime:${RUNTIME_VERSION}
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR} -DSSO_AUTH_SERVER_URL=${SSO_AUTH_SERVER_URL}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_COPY_ARGS
          value: "${ARTIFACT_COPY_ARGS}"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rest-secured
      provider: snowdrop
      version: "2.5.10-4"
      group: dev.snowdrop.example
      app.kubernetes.io/part-of: secured-api-example
      app.openshift.io/runtime-version: "2.5.10"
      app.openshift.io/runtime: rh-spring-boot
      app.kubernetes.io/name: secured-api
      app.kubernetes.io/component: frontend
    annotations:
      app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
    name: rest-secured
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: rest-secured
      provider: snowdrop
      group: dev.snowdrop.example
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rest-secured
      provider: snowdrop
      version: "2.5.10-4"
      group: dev.snowdrop.example
      app.kubernetes.io/part-of: secured-api-example
      app.openshift.io/runtime-version: "2.5.10"
      app.openshift.io/runtime: rh-spring-boot
      app.kubernetes.io/name: secured-api
      app.kubernetes.io/component: frontend
    annotations:
      app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
    name: rest-secured
  spec:
    replicas: 1
    selector:
      app: rest-secured
      provider: snowdrop
      group: dev.snowdrop.example
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: rest-secured
          provider: snowdrop
          version: "2.5.10-4"
          group: dev.snowdrop.example
          app.kubernetes.io/part-of: secured-api-example
          app.openshift.io/runtime-version: "2.5.10"
          app.openshift.io/runtime: rh-spring-boot
          app.kubernetes.io/name: secured-api
          app.kubernetes.io/component: frontend
        annotations:
          app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SSO_AUTH_SERVER_URL
            value: http://sso:8080
          image: rest-secured:2.5.10-4
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: rest-secured:2.5.10-4
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rest-secured
      provider: snowdrop
      version: "2.5.10-4"
      group: dev.snowdrop.example
      app.kubernetes.io/part-of: secured-api-example
      app.openshift.io/runtime-version: "2.5.10"
      app.openshift.io/runtime: rh-spring-boot
      app.kubernetes.io/name: secured-api
      app.kubernetes.io/component: frontend
    annotations:
      app.kubernetes.io/vcs-uri: git@github.com:snowdrop/secured-example.git
    name: rest-secured
  spec:
    path: /
    port:
      targetPort: 8080
    to:
      kind: Service
      name: rest-secured
